export const GET_COURSES_REQUEST="GET_COURSES_REQUEST"
export const GET_COURSES_SUCCESS="GET_COURSES_SUCCESS"
export const GET_COURSES_FAIL="GET_COURSES_FAIL"

export const UPDATE_MYCOURSE_REQUEST="UPDATE_MYCOURSE_REQUEST"
export const UPDATE_MYCOURSE_SUCCESS="UPDATE_MYCOURSE_SUCCESS"
export const UPDATE_MYCOURSE_FAIL="UPDATE_MYCOURSE_FAIL"

export const STUDENT_LOGOUT_SUCCESS="STUDENT_LOGOUT_SUCCESS"





