export const GET_STUDENT_REQUEST="GET_STUDENT_REQUEST"
export const GET_STUDENT_SUCCESS="GET_STUDENT_SUCCESS"
export const GET_STUDENT_FAIL="GET_STUDENT_FAIL"

export const STUDENT_LOGOUT_REQUEST="STUDENT_LOGOUT_REQUEST"
export const STUDENT_LOGOUT_SUCCESS="STUDENT_LOGOUT_SUCCESS"
export const STUDENT_LOGOUT_FAIL="STUDENT_LOGOUT_FAIL"





